### ISSUE TITLE
Calling close() before the watcher is ready does nothing

### ISSUE THREAD

**Issue by filmaj** [yuanchuan/node-watch#105]
I am testing another module that relies on node-watch. Some pseudo-code for how this module works looks like:

```
module.exports = function(callback) {
  let watcher = watch(process.cwd(), { recursive: true })
  watcher.on('change', /* some stuff here */)
  watcher.on('error', /* other stuff here */)
  if (callback) callback(null, { watcher })
}
```

It's a bit more complex but the above encapsulates the gist of it. My (tape-based) test looks something like this (pseudo-code again):

```
test('test', t => {
  myModule(function(err, { watcher }) {
    t.pass('module initialized')
    watcher.close()
    t.end()
  })
})
```

If I run this, my test script does not terminate.

After digging around, putting `console.log`s all over the place in node-watch and exposing the full internal state of the watcher in the `expose()` method, I realized that after my test called `close()`, the watcher's `_isReady` was false but `_isClosed` was true.

I can work around this by either waiting for the ready event on the watcher within either the test or my module before calling back, but I do feel like it was worth filing this issue in case you think it is worth catching this edge case.

In my opinion, it would be nice if calling `close()` soon after defining a watcher (and within the same tick) would work as expected and close / clean up appropriately. Looking through the code, it looks like the current behaviour is happening because some setup and teardown activity is postponed until the next tick, so I realize this may be easier said than done 😄

**Comment by yuanchuan** [comment]
Thanks for reporting this issue. 

It's happening because there's a async detection for `recursive` availability.

The PR fix this issue by checking internal `_isClosed` before creating a watcher, which may prevent the unnecessary traversing on Linux.

**Comment by yuanchuan** [comment]
Please try 0.7.1
