### ISSUE TITLE
Catch error when use Node 14.15.3 on Linux SysTem

### ISSUE THREAD

**Issue by lichongyang-LCY** [yuanchuan/node-watch#109]
![image](https://user-images.githubusercontent.com/26268851/104575231-e3fa2400-5691-11eb-9f27-b91e089bfc68.png)
![image](https://user-images.githubusercontent.com/26268851/104575369-ff652f00-5691-11eb-9cd8-1bdbb3b96ff3.png)
Normal operation after changing to  "recursive: false"

**Comment by lichongyang-LCY** [comment]
(node:11548) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
fs.js:1521
    throw new ERR_FEATURE_UNAVAILABLE_ON_PLATFORM('watch recursively');
    ^

TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1521:11)
    at watch (/root/xxx/node_modules/node-watch/lib/watch.js:221:8)
    at /root/xxx/node_modules/node-watch/lib/watch.js:180:14
    at Array.forEach (<anonymous>)
    at /root/xxx/node_modules/node-watch/lib/watch.js:179:13
------------------------------------------------------------------------------------------------------------------------------
watch(dir, {recursive: true, followSymLinks: true}, function (evt, filename) {});

**Comment by yuanchuan** [comment]
This was a fixed issue, please upgrade to latest version.

https://github.com/yuanchuan/node-watch/issues/94
