### ISSUE TITLE
I got this error at first use lib in nodejs using express

### ISSUE THREAD

**Issue by taryono** [yuanchuan/node-watch#110]
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const watch = require('node-watch');
const app = express(); 
watch('/', { recursive: true }, console.log);

when I run app

internal/fs/watchers.js:177
    throw error;
    ^

Error: EPERM: operation not permitted, watch '\Documents and Settings'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1415:11)
    at C:\wamp64\www\nodejs-express-sequelize-mysql\node_modules\node-watch\lib\watch.js:397:22

is it just related to permission access ?

**Comment by yuanchuan** [comment]
Yes! You might not need to watch the whole disk, try to change

```js
watch('/', { recursive: true }, console.log);
```
to 
```js
watch('./', { recursive: true }, console.log);
```

**Comment by taryono** [comment]
excelent, It's running good no errors any more...thanks @yuanchuan
