### ISSUE TITLE
New ES syntax 

### ISSUE THREAD

**Issue by yuanchuan** [yuanchuan/node-watch#113]
Maybe it's time to rewrite it with new ES syntax

**Comment by xieyuheng** [comment]
Using ES Module will make a lot of typescript users unable to upgrade to new version, because when we use `"module": "commonjs"` in `tsconfig.json`, we get:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module ... from ... not supported.
```

**Comment by yuanchuan** [comment]
I've decided not to touch the code unless necessary :)
