### ISSUE TITLE
Anyway to exclude dirs for recursive watching?

### ISSUE THREAD

**Issue by chemzqm** [yuanchuan/node-watch#12]
Is there any option can be used to configure the dirs I don't want to watch like `node_modules`?

**Comment by jmls** [comment]
did you ever get round to implementing this functionality ? thanks.

**Comment by yuanchuan** [comment]
Sorry I've being stucked for a long time. Maybe it's better off rewriting it or something.

**Comment by tunnckoCore** [comment]
@yuanchuan yea definitely, I'll review it again and will come with something. There's a lot things changed since than i.e. `micromatch` appears.

**Comment by tunnckoCore** [comment]
@jmls try / look https://github.com/wearefractal/glob-watcher and https://github.com/shama/gaze

**Comment by yuanchuan** [comment]
@tunnckoCore  actually I was since planning to write enough tests before moving to fix bugs or add new features, but never finished.  https://github.com/yuanchuan/node-watch/tree/test
