### ISSUE TITLE
fs.watch() not detecting changes to file from git operation 

### ISSUE THREAD

**Issue by tumblingG** [yuanchuan/node-watch#126]
can we fix this problem?

https://github.com/nodejs/node/issues/5039

**Comment by yuanchuan** [comment]
After some modifications to a local git repo, it outputs:

```text
❯ ./watch .
update .git/.gitstatus.N0Qvnh
update .git/.gitstatus.N0Qvnh/a
update .git/.gitstatus.N0Qvnh/b
remove .git/.gitstatus.N0Qvnh/b/1
remove .git/.gitstatus.N0Qvnh/a/1
remove .git/.gitstatus.N0Qvnh/b
remove .git/.gitstatus.N0Qvnh/a
remove .git/.gitstatus.N0Qvnh
update s
remove s
```

So It works properly on my machine (macOS). 

Could you please provide more infomation and a sample test code?

**Comment by tumblingG** [comment]
![image](https://user-images.githubusercontent.com/29335868/222659568-9949b657-22ab-4616-8661-0cd721ca9bc9.png)

As shown in the figure above, when I switch branches, sometimes files and folders change together, sometimes only folders change. I tried to write a similar demo, but failed.

**Comment by yuanchuan** [comment]
>  sometimes only folders change

This is an expected behavior of `fs.watch` when a folder is being deleted. We can't fix that unless the `initial scan` is implemented. Related issue: https://github.com/yuanchuan/node-watch/issues/58
