### ISSUE TITLE
Race condition with "is"

### ISSUE THREAD

**Issue by crh3675** [yuanchuan/node-watch#19]
It seems in _watch.js_ on like 23 throws an error in situtation where files are moving at light-speed:

```
      if (fs.existsSync(fpath)) {
          memo.push(fpath, method);
          return stat(fpath)['is' + shortcuts[method]]();  
```

We get _ENOENT_ errors even though the existsSynch succeed.  It happens very seldom but it does happen.  When it does happen, the application crashes complete.  Should a simple try{} catch(){} around the _watch_ function capture this and not affect _watch_ from continuing?

**Comment by yuanchuan** [comment]
Hi @crh3675, what's the Node version that is running?

**Comment by yuanchuan** [comment]
well, I've just published v0.3.5, trying to fix this issue by avoid using `fs.existsSync`. It has been deprecated since node 4.0 anyway.

**Comment by crh3675** [comment]
0.12 is the version

**Comment by yuanchuan** [comment]
Glad you find it useful :)
