### ISSUE TITLE
can't detect the action of the remove file

### ISSUE THREAD

**Issue by webaifei** [yuanchuan/node-watch#24]

**Comment by crh3675** [comment]
Technically you can you just don't get a meaningful event.

    var watchHandler = function(filePath) {
        require('fs').stat(filePath, function(err, stat) {
            if(err && err.code == 'ENOENT') {
               // file was removed
            }
        });
    }

**Comment by yuanchuan** [comment]
Will be added in the next version.  Thanks @crh3675  for the comment.

**Comment by sromovskypeter** [comment]
Is there a way how to detect the action of removing files right now? I am not getting any event when deleting files. 

Thank you
