### ISSUE TITLE
Sometimes file changes are not detected in new directory

### ISSUE THREAD

**Issue by thehappycoder** [yuanchuan/node-watch#30]
On Mac OS X El Capitan I listen for a directory "upload" recursively.

Using finder (also tried to do it via console), I copied "abbrev" folder with some files in it to "upload/node_modules" directory.

node-watch only detected that upload/node_modules/abbrev changed (no file changes inside abbrev directory)

But sometimes node-watch also detects files inside copied directory

**Comment by thehappycoder** [comment]
Now it detected only 2 files out of 4 in the copied new directory

**Comment by thehappycoder** [comment]
Same when you delete this directory. node-watch detects that directory was deleted, but not the files in it

**Comment by yuanchuan** [comment]
A problem with fs.watch itself.

**Comment by yuanchuan** [comment]
It's the problem (behavior) of `fs.watch` itself.
