### ISSUE TITLE
behavior of options.filter

### ISSUE THREAD

**Issue by HakurouKen** [yuanchuan/node-watch#31]
Example Codes:

``` javascript
watch('myCustomDir',{
    filter: function(filename){
        return /\.js$/.test(filename);
    }
},function(filename){
    // do something else ...
})
```

What I mean is to watch all the js file in the custom directory, but the function just return with nothing.

I walk through the source code, and found these lines at the beginning of the watch function:

``` javascript
  var skip = watcher.closed || !options.filter(fpath) || (
    is.sym(fpath) && !(options.followSymLinks && options.maxSymLevel--)
  );
  if (skip) return;
```

Which means: **The path given must suit the filter, or it will return directly.**

But should the filter here only affect only on the changed files/directories ? In other words, removing the `!options.filter(fpath)` condition may be a better choice here ?

**Comment by yuanchuan** [comment]
Hi @HakurouKen，thanks for pointing that out.

Actually the codebase is a little bit of messy right now，as well as the APIs.  I'm very sorry to say that I still don't have enough time to maintain this lib these days, so leave it as it is until the totally rewrite of it.

Or try to avoid using the `filter` option，filtering inside the callback function instead.

**Comment by HakurouKen** [comment]
@yuanchuan , thanks for reply. 
"filtering inside the callback function instead" is what I actually do in my project :)
