### ISSUE TITLE
Delete files caused an error in node 0.12.x.

### ISSUE THREAD

**Issue by HakurouKen** [yuanchuan/node-watch#32]
Test platform: Windows 7.
When delete a file in nodejs 0.12.7 , a TypeError is thrown:

```
path.js:233
      throw new TypeError('Arguments to path.join must be strings');
      ^
TypeError: Arguments to path.join must be strings
    at Object.win32.join (path.js:233:13)
    at FSWatcher.<anonymous> (E:\work\game_bible_cms_proj\document\tools\node_mo
dules\node-watch\lib\watch.js:257:26)
    at FSWatcher.emit (events.js:110:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1159:12)
```

This error happend because the filename arguments is not always provided, see the doc [here](https://nodejs.org/docs/latest/api/fs.html#fs_filename_argument). 
So the `path.join(fpath, fname)` will raise that error. It usually occurs when deleting a file.

However, it works fine on node 4.5.0 and node 6.6.0. It may need a fallback logic or friendly warning, or simply drop the support for low version nodejs.

**Comment by yuanchuan** [comment]
Hope it works

**Comment by HakurouKen** [comment]
Maybe this will cause https://github.com/yuanchuan/node-watch/issues/24 in low version of nodejs?

**Comment by yuanchuan** [comment]
not sure...

**Comment by HakurouKen** [comment]
The answer is yes. I have tested version 0.4.1 on Windows/node 0.12.7. Log some tips when filename is null maybe a better choice.

**Comment by yuanchuan** [comment]
ok I'm going to work on this tomorrow
