### ISSUE TITLE
How to watch on folder add or remove

### ISSUE THREAD

**Issue by shanalikhan** [yuanchuan/node-watch#33]
Hi
How i can run the watch when new folder is added in that watched folder or any folder is removed in it

**Comment by yuanchuan** [comment]
New added folders will be watched automatically.

**Comment by shanalikhan** [comment]
yes but when folder is removed how to handle that ?

**Comment by yuanchuan** [comment]
I'm afraid that there isn't any way to unwatch a removed directory，ignoring it would be ok. 
Maybe it should be handled in future versions by providing a new method for it.

**Comment by shanalikhan** [comment]
i needed for my work , i guess i have to make a switch than
