### ISSUE TITLE
Windows issues and various error msg

### ISSUE THREAD

**Issue by ghost** [yuanchuan/node-watch#34]
@yuanchuan I can't even get this running on windows. I tried the examples from the readme. Nothing happends.

I tried on Mac, and it works. However I noticed

- removing a folder you are watching, throws errors
- no checks for absolute path
- eating a lot of CPU
- rename a sub-folder inside a folder you are listen too, didn't invoke any events

**Comment by yuanchuan** [comment]
Sorry about this :(  Please try https://github.com/paulmillr/chokidar

**Comment by crazyhuggins** [comment]
@yuanchuan I tried that one first,  but similar issues.

**Comment by yuanchuan** [comment]
OK，I'll take a look at it later

**Comment by yuanchuan** [comment]
Closing by now .. since the new release have solved a lot of bugs related to Windows. However there's still [some bugs](https://github.com/yuanchuan/node-watch#known-bugs-on-windows) under older versions of node.js.
