### ISSUE TITLE
Watcher closes right after running

### ISSUE THREAD

**Issue by Sendoushi** [yuanchuan/node-watch#37]
Hey!
Great tool by the way.

So this is my script:
```js
'use strict';

// Imports
const watch = require('node-watch');

// Start the watcher
const watcher = watch('**/*');

console.log("Starting server watch...");

// Wait for changes...
watcher.on('change', file => {
    console.log("foo");
});

// Was there an error?
watcher.on('error', err => console.error(err));
```

This is the script I'm trying to run.
Is watcher supposed to be left open? At the moment, with this script, the watcher doesn't actually "watch" it just closes right at the end of the script. Is there any option to keep the watcher open?

**Comment by yuanchuan** [comment]
The wildcard selector `**/*`  is not supported here 😢. Try the following:

```javascript
const watcher = watch('**/*');
```

And then do some filtering if needed.

**Comment by yuanchuan** [comment]
The wildcard selector `**/*`  is not supported here 😢. Try the following:

```javascript
const watcher = watch('./');
```

And then do some filtering if needed.

**Comment by Sendoushi** [comment]
Thanks. I will try.

Maybe I can contribute and "glob" sources :P
