### ISSUE TITLE
multiple listener not work

### ISSUE THREAD

**Issue by hezki** [yuanchuan/node-watch#38]
The following code
```
watch('foo.bar',function(fn){
   console.log(fn,'first listener');
});
watch('foo.bar',function(fn){
   console.log(fn,'second listener');
});
```
Will result:

> foo.bar first listener

second listener not firing

**Comment by yuanchuan** [comment]
Yes, that's a bug

**Comment by hezki** [comment]
I think, using *fileNameCache* [here](https://github.com/yuanchuan/node-watch/blob/master/lib/watch.js#L90) it's the reason for this result.

Maybe we should cache callback separately?

**Comment by yuanchuan** [comment]
Thanks @hezki . I'll check it later

**Comment by tomekmarchi** [comment]
Second this caused a lot of issues on this end during development. Good to see a fix in progress.

**Comment by yuanchuan** [comment]
It works now
