### ISSUE TITLE
filter bug for recursive watch

### ISSUE THREAD

**Issue by yangpu** [yuanchuan/node-watch#41]
the file change event doesn't be triggered in recursive directory if having filter. eg. dir is /root, change under /root is triggered, but change under /root/doc is not triggered.

`    
options =
  recursive: true
  filter: (name) ->
    path.extname(name) is '.jade'

watch dir, options, (eventType, filename) =>
  console.log "#{eventType}: #{filename}"
`

**Comment by yuanchuan** [comment]
I can't reproduce the bug. Would you provide your os name and nodejs version?

**Comment by yuanchuan** [comment]
any news?
