### ISSUE TITLE
Doesn't work with file watches

### ISSUE THREAD

**Issue by Robinfr** [yuanchuan/node-watch#44]
When you use recursive: true and watch a file together with some folders, it seems the lstat is throwing an error..

**Comment by yuanchuan** [comment]
I can't reproduce on my computer.  What's your os and node version? 

Could you provide some code samples?

**Comment by Robinfr** [comment]
It might be because the path contains a `~` for the home folder. I've tried to get samples, but it works in most cases, just not the one I need it..

**Comment by yuanchuan** [comment]
Nodejs does not recognize '~' as the home path, so that might be the reason which caused the error.  

By the way, make sure to copy the error message when you encounter the same error again.

**Comment by Robinfr** [comment]
The thing is, it never threw an error message, since you're catching the lstat error..

**Comment by yuanchuan** [comment]
i'm a bit confusing. what's the exact lstat error?

**Comment by Robinfr** [comment]
That the path doesn't exist, since Node cannot resolve the `~` to the home folder. But that error is catched in a try/catch

Op 9 mei 2017 9:02 a.m. schreef Yuán Chuān <notifications@github.com>:

i'm a bit confusing. what's the exact lstat error?

**Comment by yuanchuan** [comment]
hmm..  Any suggestions on this?

**Comment by yuanchuan** [comment]
Wait.. Did you mean the error failed to catch this way?

```js
watcher.on('error', function() {
  //
})
```

But can be caught by 

```js
try {
  watch('path_does_not_exist', function() {}
} catch (e) {
  // error
}
```

**Comment by Robinfr** [comment]
Ahh I realized I'm using an older version (0.4.1), so maybe the problem doesn't exist anymore in the latest version..

**Comment by Robinfr** [comment]
I will close this issue since it's not relevant to the latest version. Thanks for the help!
