### ISSUE TITLE
Got ENOSPC error? Read here.

### ISSUE THREAD

**Issue by dzek69** [yuanchuan/node-watch#48]
If you get ENOSPC error, but you actually have free disk space - it means that your OS watcher limit is too low and you probably want to recursively watch a big tree of files.

Follow this description to increase the limit:
https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit

@yuanchuan my suggestion would be to notice this somewhere in README to avoid confusion.

**Comment by crh3675** [comment]
We avoid the issue with watching recursive directories by creating an **inbox** folder and when files arrive there, we move them.
