### ISSUE TITLE
Get the complete list of data deleted when deleting a directory

### ISSUE THREAD

**Issue by MattiaCostamagna** [yuanchuan/node-watch#50]
Is it somehow possible to know, when deleting a directory, the list of files and subdirectories deleted with it, or at least if it was a file or a directory?

**Comment by yuanchuan** [comment]
I think this is hard :(

**Comment by yuanchuan** [comment]
Well, it's hard to achieve this unless you cached those subdirectories or files beforehand, which might not be efficient sometimes (on deep directories).

Closing the issue by now but feel free to comment.
