### ISSUE TITLE
[Question] Why use hasNativeRecursive()?

### ISSUE THREAD

**Issue by shreeve** [yuanchuan/node-watch#55]
It looks like the `recursive` option for `fs.watch` is available only on macos and Windows:

```js
if (!(common.isOSX || common.isWindows))
  common.skip('recursive option is darwin/windows specific');
```

* https://github.com/nodejs/node/blob/bf6ce47259ebfe9f6349c223cc1735726aee062d/test/parallel/test-fs-watch-recursive.js#L5-L6

If we know this, why not just check the platform quickly, instead of doing an elaborate runtime check? The nodejs tests use these helpers:

```js
exports.isWindows = process.platform === 'win32';
exports.isOSX = process.platform === 'darwin';
```

The code for hasNativeRecursive is pretty extensive:

* https://github.com/yuanchuan/node-watch/blob/master/lib/has-native-recursive.js

Is there a reason why the quick checks aren't used?

Thanks!

**Comment by yuanchuan** [comment]
The `recursive` is not available on older versions of Nodejs so that's safer to use feature detecting.

**Comment by yuanchuan** [comment]
There must be a better way though
