### ISSUE TITLE
Watcher callback triggered even after been close

### ISSUE THREAD

**Issue by fraxken** [yuanchuan/node-watch#64]
Hi,

The watcher callback is triggered even if the .close() method is called. To be exact the callback is triggered after the configured delay.

Not sure if you schedule this callback with a timeOut or something else, but we expect  .close() method to clean the timer when triggered.

We detected the problem on our Config package (reported by one user).
https://github.com/SlimIO/Config/commit/52285972ea969874f223a3a9eda3597ee0c79205

You should be able to reproduce with a case like that:
```js
const watch = require('node-watch');

const config = { delay: 500 };
const watcher = watch('yourfile', config, function() {
  console.log('triggered');
});
// Write your file here to trigger the watcher
watcher.close();
// Wait 500ms or more here
// Watcher callback triggered even if closed...
```

Best Regards,
Thomas

**Comment by yuanchuan** [comment]
Thanks for reporting!
