### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by Krinkle** [yuanchuan/node-watch#78]
Hi @yuanchuan,

You might be planning to already, but would be nice to release the recent commits soon for use in [qunitjs/qunit](https://github.com/qunitjs/qunit).

I've already landed use of `node-watch@0.5.9`, but would feel more comfortable with the adoption if these recent changes are also applied there before releasing the next version of QUnit.

Thanks for everything!

**Comment by yuanchuan** [comment]
Yes, I can't wait to :D. I'm going to release a new version `0.6.0`.

I noticed one test failed on Windows. See https://github.com/yuanchuan/node-watch/issues/79 
And I'll see if I can fix it today.

**Comment by yuanchuan** [comment]
So happy to release a new version!  Now it's `0.6.0`.
Thank you so much! It's not possible without your help!

**Comment by Krinkle** [comment]
Thanks @yuanchuan. My holiday break is coming to an end, but I'll bookmark #79 for a time (hopefully) soon, in case I'm able to help.
