### ISSUE TITLE
'remove' event not triggered on windows

### ISSUE THREAD

**Issue by kentarokai** [yuanchuan/node-watch#85]
```
home
└── dirA
    └── dirB
        └── file
```

When I remove (=Shift+Delete) `dirA` on explorer, no event triggered. 

fs.watch() seems to emit

```
rename dirA\dirB\file
change dirA\dirB
rename dirA\dirB
change dirA
rename dirA
```

so, `filtered` ( https://github.com/yuanchuan/node-watch/blob/master/lib/watch.js#L62 ) will be blank.

**Comment by yuanchuan** [comment]
Oops.. That's a  bug. I'll check it later

**Comment by yuanchuan** [comment]
Woud you tell me the Windows version, `node`, and  `node-watch` version?

**Comment by kentarokai** [comment]
- Windows 10 Pro (x64) 1803
- node 10.15. 0
- node-watch 0.6.1

**Comment by yuanchuan** [comment]
Please try 0.6.2

**Comment by kentarokai** [comment]
@yuanchuan Verified your fix. Thank you!
