### ISSUE TITLE
Warning when watching files

### ISSUE THREAD

**Issue by GingkathFox** [yuanchuan/node-watch#90]
```
(node:68807) DeprecationWarning: (node-watch) First param in callback function  is replaced with event name since 0.5.0, use  `(evt, filename) => {}` if you want to get the filename
```

Just a warning, no biggie

**Comment by yuanchuan** [comment]
Could you show me the code?

**Comment by GingkathFox** [comment]
https://github.com/yuanchuan/node-watch/blob/a0cc1646a18f8188b0b4d1c747fc7e98f67fc380/lib/watch.js#L176

looks like its triggered here: https://github.com/yuanchuan/node-watch/blob/a0cc1646a18f8188b0b4d1c747fc7e98f67fc380/lib/watch.js#L349

**Comment by yuanchuan** [comment]
Sorry I was trying to ask for the application code which produced the warning. 

The warning is necessary as the given parameter to the callback function possibly be wrong.

**Comment by GingkathFox** [comment]
oh, here it is:

```js
watcher.on('change', function() { // set up playing status watcher...
    game = JSON.parse(fs.readFileSync('./game.json', 'utf8'))
    bot.user.setActivity(game.activity) // ...and change the playing status as its updated
})
```

**Comment by yuanchuan** [comment]
The above code will not trigger the warning unless you give exactly one param to the callback:

```js
watcher.on('change', function(name) {

})
```

Which should be

```js
watcher.on('change', function(event, name) {

})
```

**Comment by GingkathFox** [comment]
oh aight, ima close this then. thanks!
