### ISSUE TITLE
linux and recursively with node 14 throws TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]

### ISSUE THREAD

**Issue by findoff** [yuanchuan/node-watch#94]
Hello, i found error with node 14

#### Simple example
```
import watch from 'node-watch';
watch('test', {recursive: true}, ()=>{
        console.log('changed');
});
```
#### Info about error
https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_caveats

**Comment by yuanchuan** [comment]
Thanks for reporting. It seems the recursive must be removed internally
