### ISSUE TITLE
multiple events for a file sent over network

### ISSUE THREAD

**Issue by GregMydlarz** [yuanchuan/node-watch#98]
https://stackoverflow.com/questions/62775064/node-watch-windows-multiple-events-for-a-file-sent-over-network

I tried the code suggested in the #23 but no results.

**Comment by yuanchuan** [comment]
There is no simple fix. How about increase the delay?

https://github.com/yuanchuan/node-watch#options

**Comment by yuanchuan** [comment]
Closing it by now. I see this is not an issue with `node-watch` itself.
